language: node_js
node_js:
  - "9"
branches:
  only:
    - master
sudo: required
dist: trusty
cache:
  directories:
    - node_modules
addons:
  chrome: stable

before_script:
  - npm install -g firebase-tools
  - npm install -g codecov

script:
  - npm run test --code-coverage
  - npm run build

after_success:
  - codecov -t $CODECOV_TOKEN
  - firebase deploy --token $FIREBASE_TOKEN --project $PROJECT_ID
