language: node_js
node_js:
  - "10"
branches:
  only:
    - master
sudo: required
dist: trusty
cache:
  directories:
    - node_modules
addons:
  chrome: stable
  apt:
    update: true

before_script:
  - npm install -g firebase-tools
  - npm install -g codecov

script:
  - npm install
  - ng test --code-coverage
  - ng build

after_success:
  - codecov -t $CODECOV_TOKEN
  - firebase deploy --token $FIREBASE_TOKEN --project $PROJECT_ID
